-- Supabase-native Aristocracy catalog, membership, purchase history, and atomic gold debit.

create table if not exists public.aristocracy_levels (
  id integer generated by default as identity primary key,
  slug text not null unique,
  name_ar text not null,
  color_primary text not null default '#E9B949',
  color_secondary text not null default '#6B3D12',
  icon_url text,
  price_gold bigint not null check (price_gold > 0),
  duration_days smallint not null default 30 check (duration_days > 0),
  sort_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.aristocracy_features (
  id bigint generated by default as identity primary key,
  level_id integer not null references public.aristocracy_levels(id) on delete cascade,
  feature_key text not null,
  name_ar text not null,
  description_ar text not null default '',
  icon text not null default '✦',
  sort_order smallint not null default 0,
  unique (level_id, feature_key)
);

create table if not exists public.aristocracy_purchases (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  level_id integer not null references public.aristocracy_levels(id),
  price_gold bigint not null check (price_gold > 0),
  duration_days smallint not null check (duration_days > 0),
  created_at timestamptz not null default now(),
  unique (user_id, request_id)
);

create index if not exists aristocracy_purchases_user_created_idx
  on public.aristocracy_purchases (user_id, created_at desc);

create table if not exists public.user_aristocracy (
  user_id uuid primary key references auth.users(id) on delete cascade,
  level_id integer not null references public.aristocracy_levels(id),
  started_at timestamptz not null,
  expires_at timestamptz not null,
  purchase_id uuid not null references public.aristocracy_purchases(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.saki_gold_ledger (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  amount bigint not null,
  balance_after bigint not null check (balance_after >= 0),
  reason text not null,
  reference_id uuid references public.aristocracy_purchases(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists saki_gold_ledger_user_created_idx
  on public.saki_gold_ledger (user_id, created_at desc);

alter table public.aristocracy_levels enable row level security;
alter table public.aristocracy_features enable row level security;
alter table public.aristocracy_purchases enable row level security;
alter table public.user_aristocracy enable row level security;
alter table public.saki_gold_ledger enable row level security;

drop policy if exists aristocracy_levels_select_active on public.aristocracy_levels;
create policy aristocracy_levels_select_active
  on public.aristocracy_levels for select to authenticated
  using (is_active = true);

drop policy if exists aristocracy_features_select_authenticated on public.aristocracy_features;
create policy aristocracy_features_select_authenticated
  on public.aristocracy_features for select to authenticated
  using (true);

drop policy if exists aristocracy_purchases_select_own on public.aristocracy_purchases;
create policy aristocracy_purchases_select_own
  on public.aristocracy_purchases for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists user_aristocracy_select_own on public.user_aristocracy;
create policy user_aristocracy_select_own
  on public.user_aristocracy for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists saki_gold_ledger_select_own on public.saki_gold_ledger;
create policy saki_gold_ledger_select_own
  on public.saki_gold_ledger for select to authenticated
  using (auth.uid() = user_id);

grant select on public.aristocracy_levels, public.aristocracy_features,
  public.aristocracy_purchases, public.user_aristocracy,
  public.saki_gold_ledger to authenticated;

insert into public.aristocracy_levels
  (slug, name_ar, color_primary, color_secondary, price_gold, duration_days, sort_order, is_active)
values
  ('knight', 'الفارس', '#8ED8FF', '#315B91', 30000, 30, 1, true),
  ('commander', 'القائد', '#FF9A58', '#8E3319', 60000, 30, 2, true),
  ('prince', 'الأمير', '#B69CFF', '#4D2D9A', 120000, 30, 3, true),
  ('legend', 'الأسطورة', '#FF8AD8', '#841F6D', 240000, 30, 4, true),
  ('emperor', 'الإمبراطور', '#FFD978', '#7C4B17', 500000, 30, 5, true),
  ('king', 'الملك', '#FFE9A6', '#A35B00', 1000000, 30, 6, true)
on conflict (slug) do update set
  name_ar = excluded.name_ar,
  color_primary = excluded.color_primary,
  color_secondary = excluded.color_secondary,
  price_gold = excluded.price_gold,
  duration_days = excluded.duration_days,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();

insert into public.aristocracy_features
  (level_id, feature_key, name_ar, description_ar, icon, sort_order)
select l.id, f.feature_key, f.name_ar, f.description_ar, f.icon, f.sort_order
from public.aristocracy_levels l
cross join (values
  ('medal', 'وسام بجانب الاسم', 'يظهر بجانب اسمك في التطبيق', '✦', 1),
  ('frame', 'إطار صورة شخصية', 'إطار فاخر لصورتك في البروفايل', '◈', 2),
  ('colored_name', 'اسم ملون', 'اسمك يظهر بلون الرتبة', 'A', 3),
  ('profile_card', 'بطاقة بروفايل خاصة', 'خلفية وبطاقة تعريف حصرية', '▣', 4),
  ('chat_bubble', 'فقاعة دردشة', 'نمط خاص للرسائل داخل الغرف', '◌', 5),
  ('room_entry', 'دخول الغرفة', 'تأثير دخول يظهر للمستخدمين', '↗', 6),
  ('exclusive_gifts', 'هدايا حصرية', 'الوصول إلى هدايا الرتبة', '◇', 7),
  ('bullet_screen', 'تعليقات طائرة', 'تأثير تعليقات مميز', '≋', 8)
) as f(feature_key, name_ar, description_ar, icon, sort_order)
where l.slug in ('knight', 'commander', 'prince', 'legend', 'emperor', 'king')
on conflict (level_id, feature_key) do update set
  name_ar = excluded.name_ar,
  description_ar = excluded.description_ar,
  icon = excluded.icon,
  sort_order = excluded.sort_order;

create or replace function public.purchase_aristocracy(
  p_level_id integer,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_level public.aristocracy_levels%rowtype;
  v_wallet public.room_wallets%rowtype;
  v_current public.user_aristocracy%rowtype;
  v_existing public.aristocracy_purchases%rowtype;
  v_purchase_id uuid;
  v_started_at timestamptz;
  v_expires_at timestamptz;
  v_balance bigint;
  v_now timestamptz := now();
  v_status jsonb;
begin
  if v_user_id is null then
    raise exception using message = 'not_authenticated';
  end if;
  if p_request_id is null then
    raise exception using message = 'invalid_purchase_request';
  end if;

  insert into public.room_wallets (user_id)
  values (v_user_id)
  on conflict (user_id) do nothing;

  select * into v_wallet
  from public.room_wallets
  where user_id = v_user_id
  for update;

  select * into v_existing
  from public.aristocracy_purchases
  where user_id = v_user_id and request_id = p_request_id;
  if found then
    select w.gold_coins into v_balance
    from public.room_wallets w where w.user_id = v_user_id;
    select jsonb_build_object(
      'level_id', ua.level_id,
      'started_at', ua.started_at,
      'expires_at', ua.expires_at,
      'level_name', l.name_ar,
      'slug', l.slug
    ) into v_status
    from public.user_aristocracy ua
    join public.aristocracy_levels l on l.id = ua.level_id
    where ua.user_id = v_user_id;
    return jsonb_build_object(
      'purchase_id', v_existing.id,
      'gold_coins', v_balance,
      'idempotent', true,
      'status', v_status
    );
  end if;

  select * into v_level
  from public.aristocracy_levels
  where id = p_level_id and is_active = true
  for share;
  if not found then
    raise exception using message = 'aristocracy_level_not_found';
  end if;

  select * into v_current
  from public.user_aristocracy
  where user_id = v_user_id
  for update;

  if found and v_current.expires_at > v_now and v_current.level_id >= p_level_id then
    raise exception using message = 'aristocracy_already_active_or_higher';
  end if;
  if v_wallet.gold_coins < v_level.price_gold then
    raise exception using message = 'insufficient_gold_coins';
  end if;

  v_started_at := v_now;
  if v_current.expires_at > v_now then
    v_started_at := v_current.expires_at;
  end if;
  v_expires_at := v_started_at + make_interval(days => v_level.duration_days::integer);
  v_purchase_id := gen_random_uuid();

  update public.room_wallets
  set gold_coins = gold_coins - v_level.price_gold,
      lifetime_spent_gold = lifetime_spent_gold + v_level.price_gold,
      wealth_level = public.calculate_wealth_level(lifetime_spent_gold + v_level.price_gold),
      updated_at = v_now
  where user_id = v_user_id
  returning gold_coins into v_balance;

  insert into public.aristocracy_purchases
    (id, request_id, user_id, level_id, price_gold, duration_days, created_at)
  values
    (v_purchase_id, p_request_id, v_user_id, v_level.id, v_level.price_gold, v_level.duration_days, v_now);

  insert into public.user_aristocracy
    (user_id, level_id, started_at, expires_at, purchase_id, updated_at)
  values
    (v_user_id, v_level.id, v_started_at, v_expires_at, v_purchase_id, v_now)
  on conflict (user_id) do update set
    level_id = excluded.level_id,
    started_at = excluded.started_at,
    expires_at = excluded.expires_at,
    purchase_id = excluded.purchase_id,
    updated_at = excluded.updated_at;

  insert into public.saki_gold_ledger
    (user_id, amount, balance_after, reason, reference_id, created_at)
  values
    (v_user_id, -v_level.price_gold, v_balance, 'aristocracy_purchase', v_purchase_id, v_now);

  v_status := jsonb_build_object(
    'level_id', v_level.id,
    'started_at', v_started_at,
    'expires_at', v_expires_at,
    'level_name', v_level.name_ar,
    'slug', v_level.slug
  );
  return jsonb_build_object(
    'purchase_id', v_purchase_id,
    'gold_coins', v_balance,
    'idempotent', false,
    'status', v_status
  );
end;
$$;

revoke all on function public.purchase_aristocracy(integer, uuid) from public;
revoke all on function public.purchase_aristocracy(integer, uuid) from anon;
grant execute on function public.purchase_aristocracy(integer, uuid) to authenticated;
